import { useEffect, useRef, useState } from "react";
import { startSimulation, type PaymentEvent } from "./api";
import { useEvents } from "./EventsContext";

type FeedRow = PaymentEvent & { phase: "verifying" | "settled" };

export function LiveSealedFeed() {
  const events = useEvents();
  const [rows, setRows] = useState<FeedRow[]>(() => events.map((e) => ({ ...e, phase: "settled" as const })));
  const seenCountRef = useRef(events.length);
  const startedRef = useRef(false);

  useEffect(() => {
    if (events.length <= seenCountRef.current) {
      seenCountRef.current = events.length;
      return;
    }
    const newOnes = events.slice(seenCountRef.current);
    seenCountRef.current = events.length;

    // The event arriving here already carries its final, real status --
    // nargo/bb proving and the Stellar testnet submission already
    // finished server-side before this SSE frame was sent. The brief
    // "sealed" phase below is a presentation choice (matching the PRD's
    // sealed-card choreography), not a simulation of verification that
    // hasn't actually happened yet.
    setRows((prev) => [...prev, ...newOnes.map((e) => ({ ...e, phase: "verifying" as const }))]);
    for (const e of newOnes) {
      setTimeout(() => {
        setRows((prev) => prev.map((r) => (r.seq === e.seq ? { ...r, phase: "settled" } : r)));
      }, 500);
    }
  }, [events]);

  async function handleStart() {
    if (startedRef.current) return;
    startedRef.current = true;
    await startSimulation();
  }

  const verified = rows.filter((r) => r.status === "verified").length;
  const rejected = rows.filter((r) => r.status === "rejected").length;

  return (
    <div>
      <div className="panel">
        <div className="counter-bar">
          <span className="count">
            <span className="ok">{verified}</span> payments settled ·{" "}
            <span className="bad">{rejected}</span> policy violations caught ·{" "}
            <span className="ok">0</span> policy violations reached settlement
          </span>
          <button className="primary" onClick={handleStart} disabled={startedRef.current}>
            {startedRef.current ? "Running (real proving + testnet, ~10-20s/payment)…" : "Start Agent Fleet"}
          </button>
        </div>

        <div className="feed">
          {rows.length === 0 && (
            <div className="empty-feed">
              No payments yet -- click "Start Agent Fleet" to begin. Each row is a real Noir
              proof generated by nargo+bb and a real Stellar testnet transaction, so rows
              arrive every ~10-20s, not instantly.
            </div>
          )}
          {rows.map((r) => (
            <FeedRowView key={r.seq} row={r} />
          ))}
        </div>
      </div>
    </div>
  );
}

function FeedRowView({ row }: { row: FeedRow }) {
  const sealed = row.phase === "verifying";
  const className = sealed ? "feed-row pending" : `feed-row ${row.status}`;

  return (
    <div className={className} title={row.rejectDetail ?? undefined}>
      <div>{row.agentName}</div>
      <div className={sealed || row.status === "verified" ? "sealed" : ""}>
        {/* Amount is never shown in the UI, pass or fail. Vendor stays
            sealed for a settled (verified) payment -- that's the entire
            confidentiality guarantee -- but is shown for a rejected one,
            since a rejected payment never actually spent anything and
            naming the vendor is useful audit transparency. */}
        {sealed && "●●●●●●"}
        {!sealed && row.status === "verified" && "●●●●●●"}
        {!sealed && row.status === "rejected" && `●●●●●● → ${row.vendor}`}
      </div>
      <div className="mono" style={{ fontSize: 11, color: "var(--text-dim)" }}>
        {!sealed && row.explorerUrl && (
          <a href={row.explorerUrl} target="_blank" rel="noreferrer" style={{ color: "inherit" }}>
            tx {row.txHash?.slice(0, 10)}… ↗
          </a>
        )}
        {!sealed && !row.explorerUrl && row.status === "rejected" && "no tx (rejected pre-chain)"}
      </div>
      <div className={`status-tag ${sealed ? "pending" : row.status}`}>
        {sealed && "⏳ verifying..."}
        {!sealed && row.status === "verified" && "✓ Policy proof verified on-chain"}
        {!sealed && row.status === "rejected" && rejectLabel(row.rejectReason)}
      </div>
    </div>
  );
}

function rejectLabel(reason?: PaymentEvent["rejectReason"]) {
  if (reason === "over_cap") return "✗ Proof rejected — over per-tx cap (treasury-wide)";
  if (reason === "vendor_not_allowlisted") return "✗ Proof rejected — vendor not allow-listed";
  return "✗ Proof rejected";
}
