import { useEffect, useRef, useState } from "react";
import { startSimulation, type PaymentEvent } from "./api";
import { useEvents } from "./EventsContext";
import { AnimatedNumber } from "./AnimatedNumber";

type FeedRow = PaymentEvent & { phase: "sealed" | "revealed" };

const SEAL_DURATION_MS = 900;

export function LiveSealedFeed() {
  const events = useEvents();
  const [rows, setRows] = useState<FeedRow[]>(() => events.map((e) => ({ ...e, phase: "revealed" as const })));
  const seenCountRef = useRef(events.length);
  const startedRef = useRef(false);

  useEffect(() => {
    if (events.length <= seenCountRef.current) {
      seenCountRef.current = events.length;
      return;
    }
    const newOnes = events.slice(seenCountRef.current);
    seenCountRef.current = events.length;

    // The event arriving here already carries its final, real status --
    // nargo/bb proving and the Stellar testnet submission already
    // finished server-side before this SSE frame was sent. The brief
    // "sealed" phase below is a presentation choice (matching the PRD's
    // sealed-card choreography), not a simulation of verification that
    // hasn't actually happened yet.
    setRows((prev) => [...prev, ...newOnes.map((e) => ({ ...e, phase: "sealed" as const }))]);
    for (const e of newOnes) {
      setTimeout(() => {
        setRows((prev) => prev.map((r) => (r.seq === e.seq ? { ...r, phase: "revealed" } : r)));
      }, SEAL_DURATION_MS);
    }
  }, [events]);

  async function handleStart() {
    if (startedRef.current) return;
    startedRef.current = true;
    await startSimulation();
  }

  const verified = rows.filter((r) => r.status === "verified").length;
  const rejected = rows.filter((r) => r.status === "rejected").length;

  return (
    <div>
      <div className="panel">
        <div className="feed-header">
          <h2 style={{ margin: 0 }}>Live Sealed Feed</h2>
          <span className="live-indicator">
            <span className="live-dot-red" />
            Live
          </span>
        </div>
        <div className="counter-bar">
          <span className="count">
            <AnimatedNumber value={verified} className="ok" /> payments settled ·{" "}
            <AnimatedNumber value={rejected} className="bad" /> violations blocked ·{" "}
            <span className="ok">0</span> violations reached settlement
          </span>
          <button className="primary" onClick={handleStart} disabled={startedRef.current}>
            {startedRef.current ? "Running (real proving + testnet, ~10-20s/payment)…" : "Start Agent Fleet"}
          </button>
        </div>

        <div className="feed">
          {rows.length === 0 && (
            <div className="empty-feed">
              No payments yet -- click "Start Agent Fleet" to begin. Each row is a real Noir
              proof generated by nargo+bb and a real Stellar testnet transaction, so rows
              arrive every ~10-20s, not instantly.
            </div>
          )}
          {rows.map((r) => (
            <FeedRowView key={r.seq} row={r} />
          ))}
        </div>
      </div>
    </div>
  );
}

function FeedRowView({ row }: { row: FeedRow }) {
  const sealed = row.phase === "sealed";
  const statusClass = sealed ? "pending" : row.status;
  const rowClassName = `feed-row ${statusClass}`;
  const now = useTicker(2000);

  return (
    <div className={rowClassName} title={row.rejectDetail ?? undefined}>
      <div className="feed-row-top">
        <span className="feed-row-agent">
          {row.agentName}
          {/* Vendor is only ever revealed for a rejected payment -- it never
              actually spent anything, so naming it is audit-useful rather
              than a confidentiality leak. A settled payment's vendor stays
              sealed along with the amount, matching the project's core
              privacy guarantee. */}
          {!sealed && row.status === "rejected" && <span className="arrow-vendor"> → {row.vendor}</span>}
        </span>
        {/* Amount is never shown in the UI, pass or fail. */}
        <span className="sealed feed-row-amount">●●●●●●</span>
      </div>
      <div className="feed-row-bottom">
        <span key={row.phase} className={`status-tag ${statusClass}`}>
          {sealed && "⏳ verifying..."}
          {!sealed && row.status === "verified" && (
            <>
              ✓ Policy proof verified on-chain
              {row.explorerUrl && (
                <a href={row.explorerUrl} target="_blank" rel="noreferrer" onClick={(e) => e.stopPropagation()}>
                  view tx →
                </a>
              )}
            </>
          )}
          {!sealed && row.status === "rejected" && <>✗ Proof rejected — {rejectLabel(row.rejectReason)}</>}
        </span>
        <span className="feed-row-time">{relativeTime(row.timestamp, now)}</span>
      </div>
    </div>
  );
}

function rejectLabel(reason?: PaymentEvent["rejectReason"]) {
  if (reason === "over_cap") return "over per-tx cap";
  if (reason === "vendor_not_allowlisted") return "vendor not in allow-list";
  return "policy violation";
}

function relativeTime(iso: string, now: number): string {
  const diffMs = Math.max(0, now - new Date(iso).getTime());
  const s = Math.floor(diffMs / 1000);
  if (s < 5) return "just now";
  if (s < 60) return `${s}s ago`;
  const m = Math.floor(s / 60);
  if (m < 60) return `${m}m ago`;
  const h = Math.floor(m / 60);
  return `${h}h ago`;
}

/** Re-renders every `intervalMs` so relative timestamps ("12s ago") stay fresh. */
function useTicker(intervalMs: number): number {
  const [now, setNow] = useState(() => Date.now());
  useEffect(() => {
    const id = setInterval(() => setNow(Date.now()), intervalMs);
    return () => clearInterval(id);
  }, [intervalMs]);
  return now;
}

