//! Unit tests for the contract's own state machine: admin auth, agent
//! registration, policy updates, and the pre-verification checks in
//! `submit_spend` (stale commitment / nonce mismatch / policy mismatch).
//!
//! What these tests deliberately do NOT cover: a `submit_spend` call that
//! reaches a real, accepting `UltraHonkVerifier::verify`. That requires a
//! real Noir proof + verification key pair generated by `nargo`/`bb`
//! against `aegis-circuit`'s `spend_proof` circuit, and neither tool is
//! available in this build environment (see the repo README). The
//! `submit_spend_rejects_invalid_proof_bytes` test below confirms the
//! integration point is wired up -- a syntactically-invalid proof is
//! correctly rejected -- but it cannot exercise the accept path.

use super::*;
use soroban_sdk::testutils::Address as _;
use soroban_sdk::{Bytes, BytesN, Env};

fn setup(env: &Env) -> (Address, Address, BytesN<32>) {
    let contract_id = env.register(AegisTreasury, ());
    let admin = Address::generate(env);
    let root = BytesN::from_array(env, &[1u8; 32]);
    (contract_id, admin, root)
}

fn dummy_vk(env: &Env) -> Bytes {
    Bytes::from_array(env, &[0u8; 16])
}

#[test]
fn init_and_register_agent() {
    let env = Env::default();
    env.mock_all_auths();
    let (contract_id, admin, root) = setup(&env);
    let client = AegisTreasuryClient::new(&env, &contract_id);

    client.init(&admin, &root, &dummy_vk(&env));

    let commitment = BytesN::from_array(&env, &[7u8; 32]);
    client.register_agent(&admin, &1u64, &commitment);

    assert_eq!(client.get_commitment(&1u64), Some(commitment));
    assert_eq!(client.get_nonce(&1u64), 0u64);
}

#[test]
fn register_agent_rejects_non_admin() {
    let env = Env::default();
    env.mock_all_auths();
    let (contract_id, admin, root) = setup(&env);
    let client = AegisTreasuryClient::new(&env, &contract_id);
    client.init(&admin, &root, &dummy_vk(&env));

    let attacker = Address::generate(&env);
    let commitment = BytesN::from_array(&env, &[7u8; 32]);
    let result = client.try_register_agent(&attacker, &1u64, &commitment);

    assert_eq!(result, Err(Ok(Error::Unauthorized)));
}

#[test]
fn update_policy_rejects_non_admin() {
    let env = Env::default();
    env.mock_all_auths();
    let (contract_id, admin, root) = setup(&env);
    let client = AegisTreasuryClient::new(&env, &contract_id);
    client.init(&admin, &root, &dummy_vk(&env));

    let attacker = Address::generate(&env);
    let new_root = BytesN::from_array(&env, &[2u8; 32]);
    let result = client.try_update_policy(&attacker, &500u64, &new_root);

    assert_eq!(result, Err(Ok(Error::Unauthorized)));
}

#[test]
fn update_policy_as_admin_succeeds() {
    let env = Env::default();
    env.mock_all_auths();
    let (contract_id, admin, root) = setup(&env);
    let client = AegisTreasuryClient::new(&env, &contract_id);
    client.init(&admin, &root, &dummy_vk(&env));

    let new_root = BytesN::from_array(&env, &[2u8; 32]);
    client.update_policy(&admin, &500u64, &new_root);
}

fn registered_agent(env: &Env) -> (Address, BytesN<32>, Address, BytesN<32>) {
    let (contract_id, admin, root) = setup(env);
    let client = AegisTreasuryClient::new(env, &contract_id);
    client.init(&admin, &root, &dummy_vk(env));
    client.update_policy(&admin, &500u64, &root);

    let commitment = BytesN::from_array(env, &[7u8; 32]);
    client.register_agent(&admin, &1u64, &commitment);
    (contract_id, root, admin, commitment)
}

fn base_public_inputs(root: &BytesN<32>, commitment: &BytesN<32>) -> SpendPublicInputs {
    SpendPublicInputs {
        old_balance_commitment: commitment.clone(),
        new_balance_commitment: commitment.clone(),
        per_tx_cap: 500,
        vendor_allowlist_root: root.clone(),
        agent_id: 1,
        agent_nonce: 0,
    }
}

#[test]
fn submit_spend_rejects_stale_commitment() {
    let env = Env::default();
    env.mock_all_auths();
    let (contract_id, root, _admin, commitment) = registered_agent(&env);
    let client = AegisTreasuryClient::new(&env, &contract_id);

    let wrong_commitment = BytesN::from_array(&env, &[9u8; 32]);
    let mut inputs = base_public_inputs(&root, &commitment);
    inputs.old_balance_commitment = wrong_commitment;

    let result = client.try_submit_spend(&1u64, &Bytes::from_array(&env, &[0u8; 32]), &inputs);
    assert_eq!(result, Err(Ok(Error::StaleCommitment)));
}

#[test]
fn submit_spend_rejects_nonce_mismatch() {
    let env = Env::default();
    env.mock_all_auths();
    let (contract_id, root, _admin, commitment) = registered_agent(&env);
    let client = AegisTreasuryClient::new(&env, &contract_id);

    let mut inputs = base_public_inputs(&root, &commitment);
    inputs.agent_nonce = 5; // agent's stored nonce is 0

    let result = client.try_submit_spend(&1u64, &Bytes::from_array(&env, &[0u8; 32]), &inputs);
    assert_eq!(result, Err(Ok(Error::NonceMismatch)));
}

#[test]
fn submit_spend_rejects_allowlist_root_mismatch() {
    let env = Env::default();
    env.mock_all_auths();
    let (contract_id, root, _admin, commitment) = registered_agent(&env);
    let client = AegisTreasuryClient::new(&env, &contract_id);

    let mut inputs = base_public_inputs(&root, &commitment);
    inputs.vendor_allowlist_root = BytesN::from_array(&env, &[0xAB; 32]);

    let result = client.try_submit_spend(&1u64, &Bytes::from_array(&env, &[0u8; 32]), &inputs);
    assert_eq!(result, Err(Ok(Error::AllowlistRootMismatch)));
}

#[test]
fn submit_spend_rejects_per_tx_cap_mismatch() {
    let env = Env::default();
    env.mock_all_auths();
    let (contract_id, root, _admin, commitment) = registered_agent(&env);
    let client = AegisTreasuryClient::new(&env, &contract_id);

    let mut inputs = base_public_inputs(&root, &commitment);
    inputs.per_tx_cap = 999;

    let result = client.try_submit_spend(&1u64, &Bytes::from_array(&env, &[0u8; 32]), &inputs);
    assert_eq!(result, Err(Ok(Error::PerTxCapMismatch)));
}

/// All the contract's own pre-checks pass (commitment, nonce, policy all
/// match on-chain state), so this reaches the real `UltraHonkVerifier`.
/// The dummy VK installed in `init` is intentionally too short to parse,
/// so this proves the verifier integration point is actually being
/// invoked rather than silently skipped.
#[test]
fn submit_spend_rejects_invalid_proof_bytes() {
    let env = Env::default();
    env.mock_all_auths();
    let (contract_id, root, _admin, commitment) = registered_agent(&env);
    let client = AegisTreasuryClient::new(&env, &contract_id);

    let inputs = base_public_inputs(&root, &commitment);
    let result = client.try_submit_spend(&1u64, &Bytes::from_array(&env, &[0u8; 32]), &inputs);

    assert_eq!(result, Err(Ok(Error::VkLoadFailed)));
}

#[test]
fn submit_spend_unregistered_agent_fails() {
    let env = Env::default();
    env.mock_all_auths();
    let (contract_id, admin, root) = setup(&env);
    let client = AegisTreasuryClient::new(&env, &contract_id);
    client.init(&admin, &root, &dummy_vk(&env));
    client.update_policy(&admin, &500u64, &root);

    let commitment = BytesN::from_array(&env, &[7u8; 32]);
    let inputs = base_public_inputs(&root, &commitment);
    let result = client.try_submit_spend(&42u64, &Bytes::from_array(&env, &[0u8; 32]), &inputs);

    assert_eq!(result, Err(Ok(Error::AgentNotRegistered)));
}

#[test]
fn start_attestation_period_rejects_non_admin() {
    let env = Env::default();
    env.mock_all_auths();
    let (contract_id, _root, _admin, _commitment) = registered_agent(&env);
    let client = AegisTreasuryClient::new(&env, &contract_id);

    let attacker = Address::generate(&env);
    let result = client.try_start_attestation_period(&attacker, &1u64);
    assert_eq!(result, Err(Ok(Error::Unauthorized)));
}

#[test]
fn set_period_start_commitment_rejects_non_admin() {
    let env = Env::default();
    env.mock_all_auths();
    let (contract_id, _root, _admin, _commitment) = registered_agent(&env);
    let client = AegisTreasuryClient::new(&env, &contract_id);

    let attacker = Address::generate(&env);
    let historical_commitment = BytesN::from_array(&env, &[5u8; 32]);
    let result = client.try_set_period_start_commitment(&attacker, &1u64, &historical_commitment);
    assert_eq!(result, Err(Ok(Error::Unauthorized)));
}

#[test]
fn set_period_start_commitment_as_admin_is_used_by_verify_attestation() {
    let env = Env::default();
    env.mock_all_auths();
    let (contract_id, _root, admin, _commitment) = registered_agent(&env);
    let client = AegisTreasuryClient::new(&env, &contract_id);
    client.init_attestation_vk(&admin, &dummy_vk(&env));

    // A real historical commitment, distinct from the agent's current one --
    // simulating "24 hours ago" -- set directly rather than snapshotted.
    let historical_commitment = BytesN::from_array(&env, &[5u8; 32]);
    client.set_period_start_commitment(&admin, &1u64, &historical_commitment);

    // verify_attestation reads PeriodStartCommitment from storage, so a
    // subsequent call proceeds past NoPeriodStarted (reaches the real
    // verifier, which then rejects the dummy proof bytes) -- proving the
    // historical commitment was actually stored and used, not ignored.
    let claim = AttestationClaim { max_spend: 1000, period_label: 202602 };
    let result =
        client.try_verify_attestation(&1u64, &claim, &Bytes::from_array(&env, &[0u8; 32]));
    assert_eq!(result, Err(Ok(Error::AttestationVkLoadFailed)));
}

#[test]
fn verify_attestation_without_period_start_fails() {
    let env = Env::default();
    env.mock_all_auths();
    let (contract_id, _root, admin, _commitment) = registered_agent(&env);
    let client = AegisTreasuryClient::new(&env, &contract_id);
    client.init_attestation_vk(&admin, &dummy_vk(&env));

    let claim = AttestationClaim { max_spend: 1000, period_label: 202602 };
    let result =
        client.try_verify_attestation(&1u64, &claim, &Bytes::from_array(&env, &[0u8; 32]));
    assert_eq!(result, Err(Ok(Error::NoPeriodStarted)));
}

#[test]
fn verify_attestation_rejects_invalid_proof_bytes() {
    let env = Env::default();
    env.mock_all_auths();
    let (contract_id, _root, admin, _commitment) = registered_agent(&env);
    let client = AegisTreasuryClient::new(&env, &contract_id);
    client.init_attestation_vk(&admin, &dummy_vk(&env));
    client.start_attestation_period(&admin, &1u64);

    let claim = AttestationClaim { max_spend: 1000, period_label: 202602 };
    let result =
        client.try_verify_attestation(&1u64, &claim, &Bytes::from_array(&env, &[0u8; 32]));

    // Reaches the real verifier (period started, VK installed) and is
    // correctly rejected since the dummy VK is too short to parse.
    assert_eq!(result, Err(Ok(Error::AttestationVkLoadFailed)));
}
